const fs=require('node:fs');
const assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=process.env.APP_SOURCE||process.cwd();
const shots=process.env.SCREENSHOT_DIR||'/tmp/adguard-ui-review';
fs.mkdirSync(shots,{recursive:true});
const cleanSvg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="#85efc3" d="M3 3h18v18H3z"/></svg>';
const ids=['youtube','tiktok','netflix','twitch','discord','instagram','facebook','snapchat','reddit','telegram','whatsapp','steam','epic_games','roblox','minecraft','xboxlive','playstation','amazon','ebay','aliexpress',...Array.from({length:45},(_,i)=>'service_'+i)];
const names={youtube:'YouTube',tiktok:'TikTok',netflix:'Netflix',twitch:'Twitch',discord:'Discord',instagram:'Instagram',steam:'Steam',epic_games:'Epic Games',roblox:'Roblox'};
const services=ids.map((id,i)=>({id,name:names[id]||id.replaceAll('_',' '),icon_svg:i%2?cleanSvg:Buffer.from(cleanSvg).toString('base64')}));
const safe={enabled:true,bing:true,duckduckgo:true,ecosia:true,google:true,pixabay:true,yandex:true,youtube:true};
const globalConfig={filtering_enabled:true,parental_enabled:true,safebrowsing_enabled:true,safe_search:safe,blocked_services:{ids,schedule:{time_zone:'Europe/Madrid'}},protection_enabled:true};
const clients=['iMac de Emma','iMac de Martín','iPad familiar',...Array.from({length:7},(_,i)=>'Dispositivo '+(i+1))].map((name,i)=>({name,ids:['192.168.1.'+(20+i)],use_global_settings:true,use_global_blocked_services:true,filtering_enabled:true,parental_enabled:true,safebrowsing_enabled:true,safe_search:safe,blocked_services:[],upstreams:[],tags:['device_pc'],ignore_querylog:false,ignore_statistics:false,upstreams_cache_enabled:false,upstreams_cache_size:0}));
const effective={filtering_enabled:true,parental_enabled:true,safebrowsing_enabled:true,safe_search:safe,blocked_services:ids,blocked_services_schedule:{time_zone:'Europe/Madrid'},protection_enabled:true};
const state={clients,base_clients:Object.fromEntries(clients.map(c=>[c.name,c])),effective:Object.fromEntries(clients.map(c=>[c.name,effective])),base_effective:Object.fromEntries(clients.map(c=>[c.name,effective])),services,global_config:globalConfig,leases:[{client:'iMac de Emma',service:'youtube',expires:Date.now()/1000+1200},{client:'iMac de Emma',service:'service_44',expires:Date.now()/1000+1800}],events:[],requests:[],supported_tags:['device_pc','device_phone','user_child'],auto_clients:[],server:{},demo:true,error:''};
const native={configured:true,devices:[{id:'ABC',key:'nintendo:ABC',name:'Switch de Martín',model:'Switch',used_minutes:0,remaining_minutes:5,limit_minutes:0,extra_minutes:5,bedtime:'20:00',forced_termination:true,alarms_enabled:false,last_sync:Date.now()/1000,console_sync_pending:false,available:true,can_grant:true,can_cancel:true,pending_operation:null,daily_extra_minutes:5,budget_remaining_minutes:5,bedtime_remaining_minutes:600,base_bedtime:'20:00',bedtime_start:'06:00',native_policy:{timerMode:'DAILY',restrictionMode:'FORCED_TERMINATION',dailyRegulations:{timeToPlayInOneDay:{enabled:true,limitTime:0},bedtime:{enabled:true,endingTime:{hour:20,minute:0},startingTime:{hour:6,minute:0}}},eachDayOfTheWeekRegulations:{}},policy_revision:'fixture-revision'}]};
const requests=[{id:1,user_id:2,username:'martin',client:'nintendo:ABC',service:'@nintendo',minutes:20,reason:'Jugar con mis amigos',status:'pending',created:Date.now()/1000,extend_bedtime:true,approved_extend_bedtime:null}];
const user={id:1,username:'admin',role:'admin',clients:[],edit_policy:true,max_minutes:1440};
const calls=[];let adguardDown=false;
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||['/usr/bin/chromium','/usr/bin/google-chrome','/opt/google/chrome/chrome'].find(fs.existsSync),headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-breakpad','--disable-crash-reporter']});
 try{
 const context=await browser.newContext({viewport:{width:1440,height:1080}});
 await context.route('**/*',async route=>{
  const req=route.request(),url=new URL(req.url());
  if(url.pathname.startsWith('/api/')){
   if(url.pathname==='/api/state'&&adguardDown)return route.fulfill({status:502,contentType:'application/json',body:JSON.stringify({error:'AdGuard unavailable fixture'})});
   const path=url.pathname.slice(5);let body=null;
   if(req.method()==='POST'){body=req.postDataJSON();calls.push({path,body});}
   if(path==='nintendo/operation/close'&&body){
    native.devices[0].pending_operation=null;native.devices[0].can_grant=true;
    native.devices[0].last_operation={operation_id:body.operation_id,status:'superseded',message:'Seguimiento cerrado sin reenviar tiempo.'};
    return route.fulfill({contentType:'application/json',body:JSON.stringify(native.devices[0].last_operation)});
   }
   const data=path==='me'?{user,csrf:'fixture-csrf'}:path==='state'?state:path==='nintendo/state'?native:path==='requests'?{requests}:path==='auth/status'?{configured:true}:path==='nintendo/config'?{configured:true,timezone:'Europe/Madrid'}:path==='server'?{url:'http://192.168.1.2:3000',username:'admin',demo:true}:path==='diagnostics'?{entries:[]}:body?{ok:true,status:['permit','cancel','nintendo/policy'].includes(path)?'confirmed':undefined}:{ok:true};
   return route.fulfill({contentType:'application/json',body:JSON.stringify(data)});
  }
  if(url.pathname==='/')return route.fulfill({contentType:'text/html',body:fs.readFileSync(root+'/index.html','utf8')});
  return route.fulfill({status:404,body:'not found'});
 });
 const page=await context.newPage();page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://preview.local/');await page.locator('[data-client-card]').first().waitFor();
 assert.equal(await page.locator('[data-client-card]').count(),10);
 assert.equal(await page.locator('[data-client-card] .service-detail').count(),0);
 const sanitizer=await page.evaluate(()=>{const source='<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" onload="window.bad=1"><script>window.bad=1</script><foreignObject><div>evil</div></foreignObject><path d="M0 0h2v2z" fill="url(https://evil.test/a)" style="fill:red" onclick="window.bad=2" xlink:href="https://evil.test/a"/><image href="https://evil.test/a"/></svg>';const svg=safeServiceSvg(source);return {markup:svg?.outerHTML,bad:window.bad||null,base64:!!safeServiceSvg(btoa('<svg><path d="M0 0h1v1z"/></svg>'))}});
 assert.ok(sanitizer.base64);assert.equal(sanitizer.bad,null);assert.ok(!/script|foreignObject|onload|onclick|href|style=|url\(/.test(sanitizer.markup));
 await page.screenshot({path:shots+'/desktop-clientes.png',fullPage:true});
 await page.locator('[data-client-card="iMac de Emma"]').click();
 await page.locator('#adguard-dialog-backdrop').waitFor();
 assert.ok(await page.locator('#adguard-service-list [data-service-row="service_44"]').isVisible());
 await page.screenshot({path:shots+'/desktop-favoritos.png'});
 await page.getByRole('button',{name:'Todos los servicios',exact:true}).click();
 assert.ok(await page.locator('#adguard-service-list .service-category').count()>2);
 assert.equal(await page.locator('#adguard-service-list .service-category[open]').count(),0);
 await page.screenshot({path:shots+'/desktop-todos.png'});
 await page.locator('#adguard-service-list .service-category').filter({hasText:'Juegos'}).locator('summary').click();
 await page.locator('#adguard-service-list [data-favorite="steam"]').click();
 assert.ok(await page.locator('#adguard-service-list .service-category').filter({hasText:'Juegos'}).evaluate(d=>d.open));
 await page.evaluate(()=>refresh(true));
 assert.ok(await page.locator('#adguard-service-list .service-category').filter({hasText:'Juegos'}).evaluate(d=>d.open));
 await page.locator('#adguard-service-search').fill('Steam');
 assert.equal(await page.locator('#adguard-service-list [data-service-row]').count(),1);
 await page.getByRole('button',{name:'⚙ Ajustes',exact:true}).click();
 await page.locator('#c-name').fill('iMac de Emma · borrador');
 await page.evaluate(()=>refresh(false));assert.equal(await page.locator('#c-name').inputValue(),'iMac de Emma · borrador');
 await page.screenshot({path:shots+'/desktop-ajustes.png'});
 page.once('dialog',d=>d.accept());await page.locator('#adguard-dialog-backdrop').getByRole('button',{name:'Cerrar',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:shots+'/movil-clientes.png',fullPage:true});
 await page.locator('[data-client-card="iMac de Emma"]').click();
 await page.getByRole('button',{name:'Todos los servicios',exact:true}).click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:shots+'/movil-todos.png'});
 await page.getByRole('button',{name:'⚙ Ajustes',exact:true}).click();
 await page.screenshot({path:shots+'/movil-ajustes.png'});
 await page.locator('#adguard-dialog-backdrop').getByRole('button',{name:'Cerrar',exact:true}).click();
 await page.locator('[data-console="nintendo:ABC"]').click();
 assert.ok(await page.getByRole('button',{name:'Añadir tiempo extra',exact:true}).isEnabled());
 assert.ok(await page.getByRole('button',{name:'Retirar ampliación de hoy',exact:true}).isVisible());
 assert.ok(await page.locator('[data-nintendo-preview]').innerText().then(t=>t.includes('40 minutos más')));
 native.devices[0].bedtime_remaining_minutes=10;
 await page.evaluate(()=>refreshNintendoOnly());
 await page.getByLabel('Minutos extra de juego').selectOption('15');
 assert.equal(await page.locator('[data-extend-bedtime]').isChecked(),false);
 assert.equal(await page.getByRole('button',{name:'Añadir tiempo extra',exact:true}).isDisabled(),false);
 assert.ok((await page.locator('[data-nintendo-preview]').innerText()).includes('se mantiene la hora tope'));
 await page.getByRole('button',{name:'Añadir tiempo extra',exact:true}).click();
 await page.waitForFunction(()=>!busy);
 const budgetOnly=calls.find(c=>c.path==='permit'&&c.body.client==='nintendo:ABC');
 assert.equal(budgetOnly.body.minutes,15);assert.equal(budgetOnly.body.extend_bedtime,false);
 native.devices[0].bedtime_remaining_minutes=600;
 await page.evaluate(()=>refreshNintendoOnly());
 assert.ok(await page.getByRole('button',{name:'+60 min',exact:true}).isVisible());
 await page.locator('[data-extend-bedtime]').check();
 await page.screenshot({path:shots+'/movil-nintendo.png'});
 await page.locator('#nintendo-dialog-backdrop').getByRole('button',{name:'Cerrar',exact:true}).click();
 await page.locator('[data-console="nintendo:ABC"]').click();assert.equal(await page.locator('[data-extend-bedtime]').isChecked(),true);await page.evaluate(()=>refreshNintendoOnly());assert.equal(await page.locator('[data-extend-bedtime]').isChecked(),true);
 native.devices[0].extra_minutes=10;native.devices[0].daily_extra_minutes=10;native.devices[0].remaining_minutes=10;native.devices[0].budget_remaining_minutes=10;
 await page.evaluate(()=>refreshNintendoOnly());
 assert.equal(await page.locator('[data-nintendo-detail="Tiempo extra diario concedido"]').innerText(),'Tiempo extra diario concedido\n10 min');
 assert.equal(await page.locator('[data-extend-bedtime]').isChecked(),true);
 page.once('dialog',async d=>{assert.ok(d.message().includes('app oficial'));await d.accept()});
 await page.getByRole('button',{name:'Retirar ampliación de hoy',exact:true}).click();
 await page.waitForFunction(()=>!busy);
 const cancellation=calls.find(c=>c.path==='cancel');assert.ok(cancellation);
 assert.equal(cancellation.body.cancel_all_today,true);assert.equal(cancellation.body.expected_extra_minutes,10);assert.equal(cancellation.body.expected_bedtime,'20:00');
 native.devices[0].can_cancel=false;native.devices[0].extra_minutes=0;native.devices[0].daily_extra_minutes=0;
 await page.evaluate(()=>refreshNintendoOnly());
 await page.locator('#nintendo-dialog-backdrop').getByRole('button',{name:'Ajustes',exact:true}).click();
 await page.locator('#np-daily-limit').fill('90');
 await page.evaluate(()=>refresh(false));assert.equal(await page.locator('#np-daily-limit').inputValue(),'90');
 await page.locator('#nintendo-dialog-backdrop').getByRole('button',{name:'Jugar solo con permiso · 0 min diarios',exact:true}).click();
 assert.equal(await page.locator('#np-daily-limit').inputValue(),'0');
 assert.equal(await page.locator('#n-policy-forced').isChecked(),true);
 await page.locator('#nintendo-dialog-backdrop').getByRole('button',{name:'Guardar ajustes habituales',exact:true}).click();
 await page.waitForFunction(()=>!busy);
 const policy=calls.find(c=>c.path==='nintendo/policy');assert.ok(policy);assert.equal(policy.body.patch.daily.limit_minutes,0);assert.equal(policy.body.revision,'fixture-revision');
 await page.screenshot({path:shots+'/movil-nintendo-ajustes.png'});
 native.devices[0].extra_minutes=native.devices[0].daily_extra_minutes=75;
 native.devices[0].used_minutes=40;native.devices[0].remaining_minutes=native.devices[0].budget_remaining_minutes=35;
 native.devices[0].can_grant=false;native.devices[0].can_cancel=false;native.devices[0].last_read_at=Date.now()/1000;
 native.devices[0].pending_operation={operation_id:'direct:1:pending-fixture',kind:'grant',status:'pending',stage:'update_sent',minutes:15,confirmed_minutes:0,last_step_acknowledged:true,baseline_daily_extra_minutes:45,expected_daily_extra_minutes:60,expected_bedtime:'20:00',native_response_status:'TO_ADDED',waiting_seconds:300};
 await page.evaluate(()=>{dirty=false;nintendoModalTab='extra';return refreshNintendoOnly()});
 const tracking=page.locator('#nintendo-dialog-backdrop');
 assert.ok((await tracking.innerText()).includes('Aceptada · Falta verificar en Nintendo'));
 await tracking.locator('summary').filter({hasText:'Detalles del seguimiento'}).click();
 assert.ok((await tracking.locator('pre').innerText()).includes('"observed_daily_extra": 75'));
 assert.ok((await tracking.locator('pre').innerText()).includes('"expected_daily_extra": 60'));
 const nativeWrites=calls.filter(c=>['permit','cancel','nintendo/policy'].includes(c.path)).length;
 page.once('dialog',async d=>{assert.ok(d.message().includes('No se añade, retira ni reenvía tiempo'));await d.accept()});
 await tracking.getByRole('button',{name:'Cerrar seguimiento',exact:true}).click();
 await page.waitForFunction(()=>!busy);
 assert.equal(calls.filter(c=>['permit','cancel','nintendo/policy'].includes(c.path)).length,nativeWrites);
 const closed=calls.find(c=>c.path==='nintendo/operation/close');assert.equal(closed.body.expected_daily_extra_minutes,75);assert.equal(closed.body.acknowledge_uncertain,true);
 assert.equal(await tracking.getByRole('button',{name:'Cerrar seguimiento',exact:true}).count(),0);
 assert.ok((await tracking.innerText()).includes('Seguimiento cerrado sin reenviar tiempo'));
 assert.equal(native.devices[0].extra_minutes,75);
 await page.screenshot({path:shots+'/movil-nintendo-recuperado.png'});

 await page.locator('#nintendo-dialog-backdrop').getByRole('button',{name:'Cerrar',exact:true}).click();
 await page.evaluate(()=>{me={...me,role:'solicitante',id:2,clients:['iMac de Emma','nintendo:ABC']};go('clients')});
 await page.locator('[data-client-card="iMac de Emma"]').click();assert.equal(await page.locator('#adguard-dialog-backdrop').getByRole('button',{name:/Ajustes/}).count(),0);assert.ok(await page.locator('#adguard-dialog-backdrop').getByRole('button',{name:'Solicitar',exact:true}).count()>0);assert.equal(await page.locator('#adguard-dialog-backdrop').getByRole('button',{name:'Permitir',exact:true}).count(),0);
 await page.locator('#adguard-dialog-backdrop').getByRole('button',{name:'Cerrar',exact:true}).click();
 await page.locator('[data-console="nintendo:ABC"]').click();
 assert.ok(await page.locator('#nintendo-dialog-backdrop').getByRole('button',{name:'Solicitar tiempo',exact:true}).isVisible());
 assert.equal(await page.getByRole('button',{name:'Añadir tiempo extra',exact:true}).count(),0);
 assert.equal(await page.getByRole('button',{name:'Retirar ampliación de hoy',exact:true}).count(),0);
 await page.locator('#nintendo-dialog-backdrop').getByRole('button',{name:'Ajustes',exact:true}).click();assert.equal(await page.locator('#nintendo-dialog-backdrop').getByRole('button',{name:'Guardar ajustes habituales',exact:true}).count(),0);assert.equal(await page.locator('#np-daily-limit').isDisabled(),true);
 await page.locator('#nintendo-dialog-backdrop').getByRole('button',{name:'Cerrar',exact:true}).click();
 await page.evaluate(()=>{me={...me,role:'responsable',edit_policy:false,max_minutes:30};go('requests')});
 await page.locator('#review-bedtime-1').waitFor();assert.equal(await page.locator('#review-bedtime-1').isChecked(),false);
 adguardDown=true;await page.evaluate(()=>{state=null;dirty=false;go('clients');return refresh(true)});assert.ok(await page.locator('[data-console="nintendo:ABC"]').isVisible());
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({passed:true,screenshots:shots,sanitizer,calls},null,2));
 }finally{await browser.close()}
})().catch(e=>{console.error(e.stack);process.exitCode=1});
