const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const elements=new Map();const get=id=>{if(!elements.has(id))elements.set(id,{value:'',textContent:'',hidden:false,addEventListener(){}});return elements.get(id)};
const savedFavorites=new Map();
const context=vm.createContext({console,crypto:require('node:crypto').webcrypto,localStorage:{getItem:key=>savedFavorites.get(key)??null,setItem:(key,value)=>savedFavorites.set(key,value)},sessionStorage:{getItem:()=>null,setItem(){}},document:{getElementById:get,querySelectorAll:()=>[],createElement:()=>({})},window:{addEventListener(){}},navigator:{},setInterval:()=>0});
const code=fs.readFileSync('index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1].replace('start();setInterval','setInterval');vm.runInContext(fs.readFileSync('assets/client-settings.js','utf8')+'\n'+code,context);
(async()=>{
await vm.runInContext(`(async()=>{token='test';page='server';state=null;dirty=true;let calls=0,renders=0;request=async()=>{calls++;throw Object.assign(Error('Timeout'),{status:502})};render=()=>{renders++};await refresh();if(calls!==0)throw Error('Background polling must not touch server form');await refresh(true);if(renders!==0)throw Error('Network failure recreated server form');if(!dirty)throw Error('Network failure lost dirty state');page='client';await refresh();if(calls!==1)throw Error('Dirty client form must pause polling')})()`,context);
console.log('UI regression: server form preserved after failures; background polling paused for server and dirty forms');
await vm.runInContext(`(async()=>{token='test';me={role:'solicitante'};page='clients';dirty=false;state=null;lastId=null;const calls=[];request=async path=>{calls.push(path);if(path==='state')throw Object.assign(Error('AdGuard unavailable'),{status:502});return {configured:true,devices:[{key:'nintendo:ABC',name:'Switch'}]}};await refresh(true);if(!nintendoState.configured||nintendoState.devices[0].name!=='Switch')throw Error('Nintendo must load while AdGuard is unavailable');if(page!=='clients')throw Error('Nintendo clients were hidden by AdGuard failure');if(calls.join(',')!=='state,nintendo/state,requests')throw Error('Providers and approvals must use independent routes')})()`,context);
await vm.runInContext(`(async()=>{page='requests';updateNintendoOperationViews=()=>{};renderNintendoClientGrid=()=>{};renderNintendoDialogControls=()=>{};const calls=[];request=async(path,body)=>{calls.push({path,body});if(body)throw Object.assign(Error('Lost cloud response'),{status:502});return {configured:true,devices:[]}};await nintendoAction('nintendo:ABC','permit',20);const local=nintendoOperations.get('nintendo:ABC');if(!local||local.status!=='uncertain')throw Error('Lost response must remain uncertain');await refreshNintendoOnly();if(calls.filter(c=>c.body).length!==1)throw Error('Checking state replayed an additive grant');if(calls[1].path!=='nintendo/state?refresh=1')throw Error('Confirmation must use a read-only refresh');nintendoState.devices=[{key:'nintendo:ABC',last_operation:{operation_id:'direct:1:'+local.body.operation_id,status:'confirmed'}}];reconcileNintendoOperations();if(nintendoOperations.has('nintendo:ABC'))throw Error('Confirmed operation did not release controls')})()`,context);
console.log('Nintendo UI: independent state loading and read-only recovery after an uncertain grant');
await vm.runInContext(`(async()=>{request=async()=>{throw Object.assign(Error('Preflight unavailable'),{status:502,result:{operation_started:false}})};await nintendoAction('nintendo:PRE','permit',20);if(nintendoOperations.has('nintendo:PRE'))throw Error('An explicitly unsent operation became permanently uncertain')})()`,context);
vm.runInContext(`me={id:1,role:'admin'};state={services:[{id:'youtube',name:'YouTube'},{id:'discord',name:'Discord'}],base_clients:{Emma:{}},base_effective:{Emma:{blocked_services:['youtube','discord']}},leases:[]};localStorage.setItem(favoriteStorageKey('Emma'),'[]');if(clientFavorites('Emma').length)throw Error('Empty favorites were reset');localStorage.setItem(favoriteStorageKey('Emma'),'["discord"]');me={id:2,role:'solicitante'};if(clientFavorites('Emma').join(',')==='discord')throw Error('Favorites leaked between accounts');me.id=1;if(clientFavorites('Emma').join(',')!=='discord')throw Error('Saved favorites lost after switching accounts');if(allClientServices('Emma').includes('@nintendo'))throw Error('Nintendo mixed into DNS service catalog')`,context);
console.log('Client favorites: empty selections preserved and saved preferences isolated by account');
})().catch(e=>{console.error(e);process.exitCode=1});
